language: node_js
node_js: stable

branches:
  only:
  - dev

before_install:
# 解密SSH
- openssl aes-256-cbc -K $encrypted_ae690e4df1aa_key -iv $encrypted_ae690e4df1aa_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- mv -fv .travis/config ~/.ssh/config

install:
- npm install

script:
- hexo -version
- hexo clean && hexo g

after_script:
# 设置环境
- set -ev
- export TZ='Asia/Shanghai'
# 先clone原repo，得到.git提交历史
- git clone -b master git@github.com:isplit/isplit.github.io.git .deploy_git
- cd .deploy_git
- git checkout master
- mv .git/ ../public/
- cd ../public
# 添加 README
- mv ../.travis/README.md ./
# 提交
- git config user.name "isplit"
- git config user.email "i-split@outlook.com"
- git init
- git add .
- git commit -m "update:`date +"%Y-%m-%d %H:%M:%S"`"
# push
- git push -u origin master